[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Z0Z_tools"
dynamic = ["version", "description", "authors", "urls", "dependencies"]
requires-python = ">= 3.10"
readme = "README.md"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
