[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["find:"]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[project]
name = "Z0Z_tools"
dynamic = ["version", "description", "authors", "urls", "dependencies"]
requires-python = ">= 3.10"
readme = "README.md"

[project.urls]
"Homepage" = "https://github.com/hunterhogan/Z0Z_tools"
