[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Z0Z_tools"
description = "Audio processing, data structure, and package management tools."
dynamic = [
    "authors", 
    "urls", 
    "version", 
    ]
requires-python = ">= 3.10"
readme = "README.md"
dependencies = [
    "numpy",
    "packaging",
    "samplerate @ git+https://github.com/tuxu/python-samplerate.git@fix_cmake_dep ; platform_system == 'Linux' and platform_machine == 'x86_64' and python_version <= '3.10'",
    "samplerate",
    "soundfile"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[tool.setuptools.dynamic]
authors = [{ attr = "Z0Z_tools.__author__" }]
version = { attr = "Z0Z_tools.__version__" }
urls = { attr = "Z0Z_tools.__url__" }
