[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Z0Z_tools"
description = "Audio processing, data structure, and package management tools."
dynamic = [
    "authors", 
    "dependencies",
    "urls", 
    "version", 
    ]
requires-python = ">= 3.10"
readme = "README.md"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[tool.setuptools.dynamic]
authors = [{ attr = "Z0Z_tools.__author__" }]
version = { attr = "Z0Z_tools.__version__" }
dependencies = { attr = "Z0Z_tools.__dependencies__" }
urls = { attr = "Z0Z_tools.__url__" }
