[tool.poetry]
name = "Z0Z_tools"
version = "0.6.5"
description = "Solve some common Python development frustrations"
authors = ["Hunter Hogan <HunterHogan@pm.me>"]
readme = "README.md"
homepage = "https://github.com/hunterhogan/Z0Z_tools"
repository = "https://github.com/hunterhogan/Z0Z_tools.git"


[tool.poetry.dependencies]
python = ">=3.10, <3.13"
soundfile = "*"
packaging = "*"
resampy = "*"
numpy = ">2.0.0"
pytest = ">=7.0"


[tool.poetry.group.test.dependencies]
pytest = ">=7.0"
pytest-cov = "*"
pytest-mock = "*"
pandas = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = """
    --cov=Z0Z_tools
    --cov-report=term-missing
    --cov-report=xml:tests/coverage/coverage.xml
    """

[tool.coverage.run]
branch = true
source = ["Z0Z_tools"]
data_file = "tests/coverage/.coverage"
omit = [
    "Z0Z_tools/__init__.py",
    "tests/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
]

[tool.coverage.xml]
output = "tests/coverage/coverage.xml"
