import numpy
from collections.abc import Mapping
from numpy.typing import NDArray as NDArray
from typing import Any

def autoDecodingRLE(arrayTarget: NDArray[numpy.integer[Any]], addSpaces: bool = False, axisOfOperation: int | None = None) -> str: ...
def stringItUp(*scrapPile: Any) -> list[str]: ...
def updateExtendPolishDictionaryLists(*dictionaryLists: Mapping[str, list[Any] | set[Any] | tuple[Any, ...]], destroyDuplicates: bool = False, reorderLists: bool = False, killErroneousDataTypes: bool = False) -> dict[str, list[Any]]: ...
