from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

@dataclass
class ErrorMessageContext:
    parameterValue: Any = ...
    parameterValueType: str | None = ...
    containerType: str | None = ...
    isElement: bool = ...

def defineConcurrencyLimit(limit: bool | float | int | None) -> int: ...
def intInnit(listInt_Allegedly: Iterable[Any], parameterName: str | None = None, parameterType: type[Any] | None = None) -> list[int]: ...
def oopsieKwargsie(huh: Any) -> bool | None | str: ...
