import os
from Z0Z_tools.Z0Z_io import findRelativePath as findRelativePath

def makeListRequirementsFromRequirementsFile(*pathFilenames: str | os.PathLike[str]) -> list[str]: ...
def make_setupDOTpy(relativePathPackage: str | os.PathLike[str], listRequirements: list[str]) -> str: ...
def installPackageTarget(pathPackageTarget: str | os.PathLike[str]) -> None: ...
def everyone_knows_what___main___is() -> None: ...
def readability_counts() -> None: ...
def main() -> None: ...
