from Z0Z_tools import def_asTensor as def_asTensor
from numpy import dtype, float64 as float64, ndarray

def cosineWings(lengthWindow: int, ratioTaper: float | None = None) -> ndarray[tuple[int], dtype[float64]]: ...
def equalPower(lengthWindow: int, ratioTaper: float | None = None) -> ndarray[tuple[int], dtype[float64]]: ...
def halfsine(lengthWindow: int) -> ndarray[tuple[int], dtype[float64]]: ...
def tukey(lengthWindow: int, ratioTaper: float | None = None, **keywordArguments: float) -> ndarray[tuple[int], dtype[float64]]: ...
