from humpy_cytoolz._theTypes import K, K0Hashable, K1Hashable, SupportsGetItem, V, V0, V1
from collections.abc import Callable, Iterable, Mapping, MutableMapping, Sequence
from typing import Literal, overload, TypeGuard
from typing_extensions import TypeIs

__all__ = ("assoc", "assoc_in", "dissoc", "get_in", "itemfilter", "itemmap", "keyfilter", "keymap"
		, "merge", "merge_with", "update_in", "valfilter", "valmap")

@overload
def assoc(d: Mapping[K, V], key: K, value: V, factory: Callable[[], dict[K, V]] = dict) -> dict[K, V]: ...
@overload
def assoc(d: Mapping[K, V], key: K, value: V, factory: Callable[[], MutableMapping[K, V]]) -> MutableMapping[K, V]: ...
def assoc(d: Mapping[K, V], key: K, value: V, factory: Callable[[], MutableMapping[K, V]] = dict) -> MutableMapping[K, V]: ...

@overload
def assoc_in(d: Mapping[K, V], keys: Sequence[K], value: V) -> dict[K, V]: ...
@overload
def assoc_in(d: Mapping[K, V], keys: Sequence[K], value: V, factory: Callable[[], MutableMapping[K, V]]) -> MutableMapping[K, V]: ...

@overload
def dissoc(d: Mapping[K, V], *keys: K, factory: Callable[[], dict[K, V]] = dict) -> dict[K, V]: ...
@overload
def dissoc(d: Mapping[K, V], *keys: K, factory: Callable[[], MutableMapping[K, V]]) -> MutableMapping[K, V]: ...

@overload
def get_in(keys: Sequence[K], coll: SupportsGetItem[K, V], default: None = None, no_default: Literal[True] = True) -> V: ...
@overload
def get_in(keys: Sequence[K], coll: SupportsGetItem[K, V], default: None = None, no_default: bool = False) -> V | None: ...
@overload
def get_in(keys: Sequence[K], coll: SupportsGetItem[K, V], default: V, no_default: bool = False) -> V: ...

@overload
def itemfilter(predicate: Callable[[tuple[K0Hashable, V0]], TypeIs[tuple[K1Hashable, V1]]], d: Mapping[K0Hashable, V0], factory: Callable[[], dict[K1Hashable, V1]] = dict) -> dict[K1Hashable, V1]: ...
@overload
def itemfilter(predicate: Callable[[tuple[K0Hashable, V0]], TypeGuard[tuple[K1Hashable, V1]]], d: Mapping[K0Hashable, V0], factory: Callable[[], dict[K1Hashable, V1]] = dict) -> dict[K1Hashable, V1]: ...
@overload
def itemfilter(predicate: Callable[[tuple[K0Hashable, V0]], bool], d: Mapping[K0Hashable, V0], factory: Callable[[], dict[K0Hashable, V0]] = dict) -> dict[K0Hashable, V0]: ...
@overload
def itemfilter(predicate: Callable[[tuple[K0Hashable, V0]], TypeIs[tuple[K1Hashable, V1]]], d: Mapping[K0Hashable, V0], factory: Callable[[], MutableMapping[K1Hashable, V1]]) -> MutableMapping[K1Hashable, V1]: ...
@overload
def itemfilter(predicate: Callable[[tuple[K0Hashable, V0]], TypeGuard[tuple[K1Hashable, V1]]], d: Mapping[K0Hashable, V0], factory: Callable[[], MutableMapping[K1Hashable, V1]]) -> MutableMapping[K1Hashable, V1]: ...
@overload
def itemfilter(predicate: Callable[[tuple[K0Hashable, V0]], bool], d: Mapping[K0Hashable, V0], factory: Callable[[], MutableMapping[K0Hashable, V0]]) -> MutableMapping[K0Hashable, V0]: ...
def itemfilter(predicate: Callable[[tuple[K0Hashable, V0]], bool] | Callable[[tuple[K0Hashable, V0]], TypeGuard[tuple[K1Hashable, V1]]] | Callable[[tuple[K0Hashable, V0]], TypeIs[tuple[K1Hashable, V1]]], d: Mapping[K0Hashable, V0], factory: Callable[[], MutableMapping[K1Hashable, V1]] = dict) -> MutableMapping[K1Hashable, V1]:
	...

@overload
def itemmap(func: Callable[[tuple[K0Hashable, V0]], tuple[K1Hashable, V1]], d: Mapping[K0Hashable, V0], factory: Callable[..., dict[K1Hashable, V1]] = dict) -> dict[K1Hashable, V1]: ...
@overload
def itemmap(func: Callable[[tuple[K0Hashable, V0]], tuple[K1Hashable, V1]], d: Mapping[K0Hashable, V0], factory: Callable[..., MutableMapping[K1Hashable, V1]]) -> MutableMapping[K1Hashable, V1]: ...
@overload
def itemmap(func: Callable[[tuple[K0Hashable, V0]], Iterable[K1Hashable | V1]], d: Mapping[K0Hashable, V0], factory: Callable[..., dict[K1Hashable, V1]] = dict) -> dict[K1Hashable, V1]: ...
@overload
def itemmap(func: Callable[[tuple[K0Hashable, V0]], Iterable[K1Hashable | V1]], d: Mapping[K0Hashable, V0], factory: Callable[..., MutableMapping[K1Hashable, V1]]) -> MutableMapping[K1Hashable, V1]: ...
def itemmap(func: Callable[[tuple[K0Hashable, V0]], tuple[K1Hashable, V1]] | Callable[[tuple[K0Hashable, V0]], Iterable[K1Hashable | V1]], d: Mapping[K0Hashable, V0], factory: Callable[..., MutableMapping[K1Hashable, V1]] = dict) -> MutableMapping[K1Hashable, V1]:
	...

@overload
def keyfilter(predicate: Callable[[K0Hashable], TypeIs[K1Hashable]], d: Mapping[K0Hashable, V], factory: Callable[[], dict[K1Hashable, V]] = dict) -> dict[K1Hashable, V]: ...
@overload
def keyfilter(predicate: Callable[[K0Hashable], TypeGuard[K1Hashable]], d: Mapping[K0Hashable, V], factory: Callable[[], dict[K1Hashable, V]] = dict) -> dict[K1Hashable, V]: ...
@overload
def keyfilter(predicate: Callable[[K0Hashable], bool], d: Mapping[K0Hashable, V], factory: Callable[[], dict[K0Hashable, V]] = dict) -> dict[K0Hashable, V]: ...
@overload
def keyfilter(predicate: Callable[[K0Hashable], TypeIs[K1Hashable]], d: Mapping[K0Hashable, V], factory: Callable[[], MutableMapping[K1Hashable, V]]) -> MutableMapping[K1Hashable, V]: ...
@overload
def keyfilter(predicate: Callable[[K0Hashable], TypeGuard[K1Hashable]], d: Mapping[K0Hashable, V], factory: Callable[[], MutableMapping[K1Hashable, V]]) -> MutableMapping[K1Hashable, V]: ...
@overload
def keyfilter(predicate: Callable[[K0Hashable], bool], d: Mapping[K0Hashable, V], factory: Callable[[], MutableMapping[K0Hashable, V]]) -> MutableMapping[K0Hashable, V]: ...
def keyfilter(predicate: Callable[[K0Hashable], bool] | Callable[[K0Hashable], TypeGuard[K1Hashable]] | Callable[[K0Hashable], TypeIs[K1Hashable]], d: Mapping[K0Hashable, V], factory: Callable[[], MutableMapping[K1Hashable, V]] = dict) -> MutableMapping[K1Hashable, V]:
	...

@overload
def keymap(func: Callable[[K0Hashable], K1Hashable], d: Mapping[K0Hashable, V], factory: Callable[[], dict[K1Hashable, V]] = dict) -> dict[K1Hashable, V]: ...
@overload
def keymap(func: Callable[[K0Hashable], K1Hashable], d: Mapping[K0Hashable, V], factory: Callable[[], MutableMapping[K1Hashable, V]]) -> MutableMapping[K1Hashable, V]: ...
def keymap(func: Callable[[K0Hashable], K1Hashable], d: Mapping[K0Hashable, V], factory: Callable[[], MutableMapping[K1Hashable, V]] = dict) -> MutableMapping[K1Hashable, V]:
	...

@overload
def merge(*dicts: Mapping[K, V] | Iterable[Mapping[K, V]], factory: Callable[[], dict[K, V]] = dict) -> dict[K, V]: ...
@overload
def merge(*dicts: Mapping[K, V] | Iterable[Mapping[K, V]], factory: Callable[[], MutableMapping[K, V]]) -> MutableMapping[K, V]: ...
def merge(*dicts: Mapping[K, V] | Iterable[Mapping[K, V]], factory: Callable[[], MutableMapping[K, V]] = dict) -> MutableMapping[K, V]:
	...

@overload
def merge_with(func: Callable[[Sequence[V]], V], *dicts: Mapping[K, V] | Iterable[Mapping[K, V]], factory: Callable[[], dict[K, V]] = dict) -> dict[K, V]: ...
@overload
def merge_with(func: Callable[[Sequence[V]], V], *dicts: Mapping[K, V] | Iterable[Mapping[K, V]], factory: Callable[[], MutableMapping[K, V]]) -> MutableMapping[K, V]: ...
def merge_with(func: Callable[[Sequence[V]], V], *dicts: Mapping[K, V] | Iterable[Mapping[K, V]], factory: Callable[[], MutableMapping[K, V]] = dict) -> MutableMapping[K, V]:
	...

@overload
def update_in(d: Mapping[K, V], keys: Sequence[K], func: Callable[[V | None], V], default: None = None) -> dict[K, V]: ...
@overload
def update_in(d: Mapping[K, V], keys: Sequence[K], func: Callable[[V], V], default: V) -> dict[K, V]: ...
@overload
def update_in(d: Mapping[K, V], keys: Sequence[K], func: Callable[[V | None], V], default: None, factory: Callable[[], MutableMapping[K, V]]) -> MutableMapping[K, V]: ...
@overload
def update_in(d: Mapping[K, V], keys: Sequence[K], func: Callable[[V], V], default: V, factory: Callable[[], MutableMapping[K, V]]) -> MutableMapping[K, V]: ...
def update_in(d: Mapping[K, V], keys: Sequence[K], func: Callable[[V], V], default: V | None = None, factory: Callable[[], MutableMapping[K, V]] = dict) -> MutableMapping[K, V]:
	...

@overload
def valfilter(predicate: Callable[[V0], TypeIs[V1]], d: Mapping[K, V0], factory: Callable[[], dict[K, V1]] = dict) -> dict[K, V1]: ...
@overload
def valfilter(predicate: Callable[[V0], TypeGuard[V1]], d: Mapping[K, V0], factory: Callable[[], dict[K, V1]] = dict) -> dict[K, V1]: ...
@overload
def valfilter(predicate: Callable[[V0], bool], d: Mapping[K, V0], factory: Callable[[], dict[K, V0]] = dict) -> dict[K, V0]: ...
@overload
def valfilter(predicate: Callable[[V0], TypeIs[V1]], d: Mapping[K, V0], factory: Callable[[], MutableMapping[K, V1]]) -> MutableMapping[K, V1]: ...
@overload
def valfilter(predicate: Callable[[V0], TypeGuard[V1]], d: Mapping[K, V0], factory: Callable[[], MutableMapping[K, V1]]) -> MutableMapping[K, V1]: ...
@overload
def valfilter(predicate: Callable[[V0], bool], d: Mapping[K, V0], factory: Callable[[], MutableMapping[K, V0]]) -> MutableMapping[K, V0]: ...
def valfilter(predicate: Callable[[V0], bool] | Callable[[V0], TypeGuard[V1]] | Callable[[V0], TypeIs[V1]], d: Mapping[K, V0], factory: Callable[[], MutableMapping[K, V1]] = dict) -> MutableMapping[K, V1]:
	...

@overload
def valmap(func: Callable[[V0], V1], d: Mapping[K, V0], factory: Callable[[], dict[K, V1]] = dict) -> dict[K, V1]: ...
@overload
def valmap(func: Callable[[V0], V1], d: Mapping[K, V0], factory: Callable[[], MutableMapping[K, V1]]) -> MutableMapping[K, V1]: ...
def valmap(func: Callable[[V0], V1], d: Mapping[K, V0], factory: Callable[[], MutableMapping[K, V1]] = dict) -> MutableMapping[K, V1]:
	...
